"""post_category_relation

Revision ID: 1682148e09a2
Revises: 014a5eb1bcff
Create Date: 2024-07-02 12:12:17.914808

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1682148e09a2'
down_revision = '014a5eb1bcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
